default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 10
  host: <%= ENV['HOWOLD_DATABASE_HOST'] %>
  username: <%= ENV['HOWOLD_DATABASE_USERNAME'] %>
  password: <%= ENV['HOWOLD_DATABASE_PASSWORD'] %>
  socket: <%= ENV['HOWOLD_DATABASE_SOCKET'] %>

development:
  <<: *default
  database: howold_development

test:
  <<: *default
  database: howold_test

production:
  <<: *default
  database: howold_production
